package mcpserver

import "github.com/modelcontextprotocol/go-sdk/mcp"

func (a *App) register(server *mcp.Server) {
	addTool(a, server, &mcp.Tool{Name: "set_download_path", Description: "Set the default local save location for images and animations."}, a.setDownloadPath)
	addTool(a, server, &mcp.Tool{Name: "download", Description: "Download artwork IDs or supported Pixiv artwork/user URLs with intelligent storage rules."}, a.download)
	addTool(a, server, &mcp.Tool{Name: "refresh_token", Description: "Manually refresh Pixiv API token when encountering authentication errors."}, a.refreshToken)
	addTool(a, server, &mcp.Tool{Name: "set_refresh_token", Description: "Set or update the Pixiv refresh token for authentication."}, a.setRefreshToken)
	addTool(a, server, &mcp.Tool{Name: "download_random_from_recommendation", Description: "Download random artworks from recommendations."}, a.downloadRandom)
	addTool(a, server, &mcp.Tool{Name: "search_illust", Description: "Search for illustrations using keywords with filters.", InputSchema: searchIllustInputSchema(), OutputSchema: recordsOutputSchema()}, a.searchIllust)
	addTool(a, server, &mcp.Tool{Name: "search_novel", Description: "Search for novels using keywords with supported filters.", InputSchema: searchNovelInputSchema(), OutputSchema: recordsOutputSchema()}, a.searchNovel)
	addTool(a, server, &mcp.Tool{Name: "search_illust_options", Description: "List drawing tools available for an authenticated illustration search."}, a.searchIllustOptions)
	addTool(a, server, &mcp.Tool{Name: "illust_detail", Description: "Get detailed information from exactly one artwork ID or supported Pixiv URL.", OutputSchema: recordsOutputSchema()}, a.illustDetail)
	addTool(a, server, &mcp.Tool{Name: "illust_related", Description: "Find artworks related to a specific illustration.", OutputSchema: recordsOutputSchema()}, a.illustRelated)
	addTool(a, server, &mcp.Tool{Name: "illust_ranking", Description: "Browse Pixiv rankings.", OutputSchema: recordsOutputSchema()}, a.illustRanking)
	addTool(a, server, &mcp.Tool{Name: "search_user", Description: "Search for users/artists on Pixiv.", OutputSchema: recordsOutputSchema()}, a.searchUser)
	addTool(a, server, &mcp.Tool{Name: "illust_recommended", Description: "Get personalized artwork recommendations.", OutputSchema: recordsOutputSchema()}, a.illustRecommended)
	addTool(a, server, &mcp.Tool{Name: "recommended", Description: "Get typed personalized recommendations through the Pixiv SDK.", OutputSchema: recordsOutputSchema()}, a.recommended)
	addTool(a, server, &mcp.Tool{Name: "trending_tags_illust", Description: "Get currently trending illustration tags."}, a.trendingTags)
	addTool(a, server, &mcp.Tool{Name: "illust_follow", Description: "Browse artworks from followed artists.", OutputSchema: recordsOutputSchema()}, a.illustFollow)
	addTool(a, server, &mcp.Tool{Name: "novel_follow", Description: "Browse new novels from followed users through the App API.", OutputSchema: recordsOutputSchema()}, a.novelFollow)
	addTool(a, server, &mcp.Tool{Name: "illust_new", Description: "Browse latest illustrations or manga through the App API.", OutputSchema: recordsOutputSchema()}, a.illustNew)
	addTool(a, server, &mcp.Tool{Name: "novel_new", Description: "Browse latest novels through the App API.", OutputSchema: recordsOutputSchema()}, a.novelNew)
	addTool(a, server, &mcp.Tool{Name: "mypixiv_users", Description: "Browse MyPixiv users for the authenticated account through the App API.", OutputSchema: recordsOutputSchema()}, a.myPixivUsers)
	addTool(a, server, &mcp.Tool{Name: "mypixiv_illusts", Description: "Browse aggregated MyPixiv artworks through the App API.", OutputSchema: recordsOutputSchema()}, a.myPixivIllusts)
	addTool(a, server, &mcp.Tool{Name: "mypixiv_novels", Description: "Browse aggregated MyPixiv novels through the App API.", OutputSchema: recordsOutputSchema()}, a.myPixivNovels)
	addTool(a, server, &mcp.Tool{Name: "user_detail", Description: "Get a user's complete profile through the authenticated Pixiv SDK.", OutputSchema: recordsOutputSchema()}, a.userDetail)
	addTool(a, server, &mcp.Tool{Name: "user_artworks", Description: "Browse a user's artworks.", OutputSchema: recordsOutputSchema()}, a.userArtworks)
	addTool(a, server, &mcp.Tool{Name: "user_novels", Description: "Browse a user's novels through the App API.", OutputSchema: recordsOutputSchema()}, a.userNovels)
	addTool(a, server, &mcp.Tool{Name: "user_bookmarks", Description: "Browse user's bookmarked artworks.", OutputSchema: recordsOutputSchema()}, a.userBookmarks)
	addTool(a, server, &mcp.Tool{Name: "user_following", Description: "View user's following list.", OutputSchema: recordsOutputSchema()}, a.userFollowing)
	addTool(a, server, &mcp.Tool{Name: "add_bookmark", Description: "Add an artwork to bookmarks."}, a.addBookmark)
	addTool(a, server, &mcp.Tool{Name: "remove_bookmark", Description: "Remove an artwork from bookmarks."}, a.removeBookmark)
	addTool(a, server, &mcp.Tool{Name: "follow_user", Description: "Follow a Pixiv user."}, a.followUser)
	addTool(a, server, &mcp.Tool{Name: "unfollow_user", Description: "Unfollow a Pixiv user."}, a.unfollowUser)
}
