package cli

import (
	"io"
	"sort"
	"strings"
	"testing"

	"github.com/FlanChanXwO/pixiv-cli/internal/cli/pipeline"
	"github.com/FlanChanXwO/pixiv-cli/internal/cli/requirements"
	"github.com/spf13/cobra"
)

// cobraBuiltInCommands are generated by Cobra itself rather than declared by a
// command owner in this repository. They never consume our stdin contract.
var cobraBuiltInCommands = map[string]struct{}{
	"help":       {},
	"completion": {},
}

// TestEveryRunnableCommandDeclaresAnInputContract walks the real command tree
// returned by newRootCommand and requires each runnable command to carry a
// declared input contract.
//
// The contract matters because input resolution runs inside cobra's Args
// validator, before the persistent pre-run performs startup side effects. A
// command that never declares one silently falls back to cobra's default
// argument handling: it neither reserves stdin for a command-specific protocol
// (pipeline.NoInput) nor participates in the implicit-stdin contract, so
// whether it reads stdin becomes an accident of its own RunE.
//
// This asserts against the assembled tree, not source text, so it keeps
// working when commands move between packages or files.
func TestEveryRunnableCommandDeclaresAnInputContract(t *testing.T) {
	root := newTestRootCommand(t)

	missing := commandsWithoutInputContract(root)
	if len(missing) > 0 {
		t.Fatalf("runnable commands without a declared input contract:\n  %s", strings.Join(missing, "\n  "))
	}
}

// TestUndeclaredCommandIsDetected proves the check above can fail. Without it,
// a refactor that broke the walk or the annotation lookup would leave a test
// that passes for every possible command tree.
func TestUndeclaredCommandIsDetected(t *testing.T) {
	root := newTestRootCommand(t)
	root.AddCommand(&cobra.Command{
		Use:  "undeclared-probe",
		RunE: func(*cobra.Command, []string) error { return nil },
	})

	missing := commandsWithoutInputContract(root)
	if len(missing) != 1 || !strings.HasSuffix(missing[0], "undeclared-probe") {
		t.Fatalf("probe command was not detected as missing a contract, got %v", missing)
	}
}

// commandsWithoutInputContract returns the paths of runnable commands in the
// tree that carry no declared input contract, sorted for stable output.
func commandsWithoutInputContract(root *cobra.Command) []string {
	missing := make([]string, 0)
	forEachCommand(root, func(command *cobra.Command) {
		if command == root || !command.Runnable() {
			return
		}
		if _, builtIn := cobraBuiltInCommands[command.Name()]; builtIn {
			return
		}
		if _, declared := command.Annotations[pipeline.AnnotationKey]; !declared {
			missing = append(missing, command.CommandPath())
		}
	})
	sort.Strings(missing)
	return missing
}

// TestDeclaredInputContractsUseAKnownCodec rejects a malformed or unknown
// codec in the declared contract. An unrecognized codec would leave the
// resolver silently inactive while the command still looks declared.
func TestDeclaredInputContractsUseAKnownCodec(t *testing.T) {
	root := newTestRootCommand(t)

	known := map[pipeline.Codec]struct{}{
		pipeline.NoInput:      {},
		pipeline.TextValue:    {},
		pipeline.TextOrRecord: {},
	}
	unknown := make([]string, 0)
	forEachCommand(root, func(command *cobra.Command) {
		annotation, declared := command.Annotations[pipeline.AnnotationKey]
		if !declared {
			return
		}
		codec, _, ok := strings.Cut(annotation, ":")
		if !ok {
			unknown = append(unknown, command.CommandPath()+" has a malformed contract "+annotation)
			return
		}
		if _, valid := known[pipeline.Codec(codec)]; !valid {
			unknown = append(unknown, command.CommandPath()+" declares unknown codec "+codec)
		}
	})

	sort.Strings(unknown)
	if len(unknown) > 0 {
		t.Fatalf("invalid declared input contracts:\n  %s", strings.Join(unknown, "\n  "))
	}
}

// TestProtocolOwningCommandsReserveStdin pins the commands that must keep
// stdin for their own wire protocol. The MCP servers speak JSON-RPC on stdio,
// so a generic stdin resolver must never consume from them.
func TestProtocolOwningCommandsReserveStdin(t *testing.T) {
	root := newTestRootCommand(t)

	for _, args := range [][]string{{"mcp"}, {"fanbox", "mcp"}} {
		command, _, err := root.Find(args)
		if err != nil {
			t.Fatalf("find %v: %v", args, err)
		}
		annotation := command.Annotations[pipeline.AnnotationKey]
		codec, _, _ := strings.Cut(annotation, ":")
		if pipeline.Codec(codec) != pipeline.NoInput {
			t.Fatalf("%s must reserve stdin for its own protocol, declared codec %q", command.CommandPath(), codec)
		}
	}
}

func newTestRootCommand(t *testing.T) *cobra.Command {
	t.Helper()
	a := app{
		in:             strings.NewReader(""),
		out:            io.Discard,
		errOut:         io.Discard,
		resourcesState: &resourcesState{},
		debugState:     &debugState{},
	}
	root := a.newRootCommand()
	t.Cleanup(func() {
		requirements.Clear(root)
		pipeline.Clear(root)
	})
	return root
}

func forEachCommand(command *cobra.Command, visit func(*cobra.Command)) {
	visit(command)
	for _, child := range command.Commands() {
		forEachCommand(child, visit)
	}
}
